### PR TITLE
Fix: comma in css floats

### PR DESCRIPTION
**Pull request by FinesseRus**
In some system localization settings float numbers are printed with comma. But only dot is acceptable in float values in CSS. So a code that changes comma to dot is added.

### CODE REVIEW

**Comment by ChiperSoft** [comment]
It would probably be more sensible to use `number_format()` to convert the float to a string with an explicit decimal point.  Could you make that change?

**Comment by ChiperSoft** [comment]
That would also ensure that it doesn't produce an extremely long decimal. Three decimal places should be sufficient.

**Comment by FinesseRus** [comment]
What about this? `number_format($this->alpha, 2, '.', '')`

**Comment by ChiperSoft** [comment]
I'd say make it 3 places, but that's exactly what I had in mind.

**Comment by FinesseRus** [comment]
Is it OK that numbers like this `0.5` will be printed as `0.50`?

**Comment by ChiperSoft** [comment]
Yeah, that wont harm anything.  You could do `trim(number_format($this->alpha, 3, '.', '') ,'0')`

**Comment by ChiperSoft** [comment]
Actually, that wouldn't be a good idea, it'd trim off the leading 0

**Comment by FinesseRus** [comment]
I don't fully understand you. No leading zero (`.5`) is OK for CSS.

So what is the final decision?

**Comment by ChiperSoft** [comment]
Personally I don't like to leave off leading zeros. Skip the trim, just do number_format

**Comment by FinesseRus** [comment]
It's done

**Comment by ChiperSoft** [comment]
Right on, thanks!

**Comment by FinesseRus** [comment]
Thank you too for maintaining Color

**Pull request merged**
